<?php
	$a=7;
	$c=0;
    for($no=50;$no<=100;$no++)
    {
        for($i=1;$i<=$no;$i++)
        {
            if($no%$i==0)
            {
                $c++;
            }
        }
        if($c==2)
        {
            echo "$no<br>";
        }
        $c=0;
    }
?>